repo_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo05
repo_name: VerificAAA

site_url: https://unbihc2025-1.github.io/IHC-2025.1-Grupo05
site_name: VerificAAA

markdown_extensions:
  - tables
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: false

nav:
  - Início - VerificAAA: 'index.md'

  - Desenvolvimento Web:
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

theme:
  logo: imagens/logo-verificaaa.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt

extra_css:
  - assets/css/custom.css

